name: Deploy CPICSA a GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar Código
        uses: actions/checkout@v4

      - name: 🛠️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Instalar Dependencias
        run: npm ci

      - name: 🚀 Compilar Proyecto (Producción)
        # IMPORTANTE: base-href debe ser el nombre de tu repo para que carguen los estilos
        run: npx ng build --configuration production --base-href /cpicsa/

      - name: 📤 Desplegar a rama gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/cpicsa/browser 
          branch: gh-pages 
          clean: true 
          commit-message: "🚀 Deploying CPICSA to GitHub Pages"